name: juliofilizzola

on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    environment: staging
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
 
      - name: Yarn CI
        run: yarn install --frozen-lockfile
      
      - name: Yarn test
        run: yarn run test

      - name: EsLint
        run: yarn run lint
   